name: Mann Patel
email: mann.patel1@ucalgary.ca
github: mannpatel
linkedin: mannpatel
bio: "Software Developer"
location: "Alberta, Calgary"

title: Mann Patel
description: Developer

defaults:
  - scope:
      path: ""
    values:
      layout: default