name: Mann Patel
email: mann.patel1@ucalgary.ca
github: mannpatel
linkedin: mannpatel
bio: "Developer"
location: "Alberta, Calgary"

theme: jekyll-theme-minimal
title: Mann Patel
description: Developer

defaults:
  - scope:
      path: ""
    values:
      layout: default